title: Position UI GameObjects in 2D
hero_image: images/banner.png
description: Position UI GameObjects in 2D
version: 4
listed: false
copyedit: false
last_tested: "2021-11-25"
steps:
  - title: Position UI GameObjects in 2D
 
