---
title: Positionner les GameObjects UI en 2D
hero_image: images/banner.png
description: Positionner les GameObjects UI en 2D
version: 4
listed: false
copyedit: false
last_tested: "2021-11-25"
steps:
  - title: Positionner les GameObjects UI en 2D
